// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaPDV.Data;

#nullable disable

namespace SistemaPDV.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921000201_AddCartoesEBandeiraNoPagamento")]
    partial class AddCartoesEBandeiraNoPagamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("SistemaPDV.Models.Caixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AberturaSincronizada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataCaixa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TrocoFinal")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TrocoInicial")
                        .HasColumnType("TEXT");

                    b.Property<int>("Turno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimoErroSync")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.HasIndex("DataCaixa", "Turno", "FuncionarioId")
                        .IsUnique();

                    b.ToTable("Caixas");
                });

            modelBuilder.Entity("SistemaPDV.Models.Cartao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AliasCartao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandeiraId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("BandeiraNome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Credenciadora")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Dia")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Parcelas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxaAdministrativa")
                        .HasPrecision(9, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("Cartoes");
                });

            modelBuilder.Entity("SistemaPDV.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Bloqueado")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("CidadeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoDdd")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoTelefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContribuinteIcms")
                        .HasColumnType("TEXT");

                    b.Property<string>("CpfCnpj")
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataFundacao")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FuncionarioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FuncionarioNome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IndicadorFinalidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InscricaoEstadual")
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoMunicipal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pessoa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PontoReferencia")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rg")
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipoClienteId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoClienteNome")
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoErroSync")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaPDV.Models.ConfiguracaoSincronizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiClienteId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiClienteSecretProtegido")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ClienteConsumidorFinalIdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoPdv")
                        .HasMaxLength(6)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExigirAberturaCaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("NomeDispositivo")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoClientes")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoEmpresa")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoFormasPagamento")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoFuncionarios")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UltimaSincronizacaoProdutos")
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlApi")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracoesSincronizacao");
                });

            modelBuilder.Entity("SistemaPDV.Models.DigitacaoBandeiraCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("CaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.ToTable("DigitacoesBandeiraCaixa");
                });

            modelBuilder.Entity("SistemaPDV.Models.DigitacaoCaixa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.HasIndex("FormaPagamentoId");

                    b.ToTable("DigitacoesCaixa");
                });

            modelBuilder.Entity("SistemaPDV.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasColumnType("TEXT");

                    b.Property<string>("CertificadoProtegido")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complemento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ModuloFiscal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NfceAmbiente")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NfceModelo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NfceNumeroCaixa")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NfceProximoNumero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NfceSerie")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("SistemaPDV.Models.FormaPagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtalhoNumero")
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CarteiraDigital")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodigoNfce")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoTransacaoSitef")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Padrao")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PdvPos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PermissaoSupervisor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreVenda")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("FormasPagamento");
                });

            modelBuilder.Entity("SistemaPDV.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Desativado")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("PdvKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Supervisor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("SistemaPDV.Models.ItemVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AcrescimoItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DescontoItem")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Quantidade")
                        .HasPrecision(18, 3)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoId");

                    b.HasIndex("VendaId");

                    b.ToTable("ItensVenda");
                });

            modelBuilder.Entity("SistemaPDV.Models.PagamentoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bandeira")
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int>("FormaPagamentoId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VendaId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormaPagamentoId");

                    b.HasIndex("VendaId");

                    b.ToTable("PagamentosVenda");
                });

            modelBuilder.Entity("SistemaPDV.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cest")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoBeneficioFiscal")
                        .HasColumnType("TEXT");

                    b.Property<string>("CodigoNfe")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstoqueAtual")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Fabricante")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GrupoId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Hortifruit")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("MargemLucro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ncm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeOriginal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacao")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrecoCompra")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrecoVenda")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProdutoIdApi")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("PromocaoPreco")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PromocaoQuantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PromocaoValidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RestricaoIdade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusFiscal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UnidadeMedida")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Vender")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IdExterno")
                        .IsUnique();

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaPDV.Models.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("CaixaId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DescartadaEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DescartadaPorId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Desconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdExterno")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivoDescarte")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroPedido")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProximaTentativaEm")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SolicitadaPorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncStatus")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TentativasEnvio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UltimoErroSync")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VendaIdExterno")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CaixaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("NumeroPedido")
                        .IsUnique();

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("SistemaPDV.Models.Caixa", b =>
                {
                    b.HasOne("SistemaPDV.Models.Funcionario", null)
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPDV.Models.Cliente", b =>
                {
                    b.OwnsOne("SistemaPDV.Models.TabelaPreco", "TabelaPreco", b1 =>
                        {
                            b1.Property<int>("ClienteId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Descricao")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int?>("IdExterno")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ClienteId");

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("TabelaPreco");
                });

            modelBuilder.Entity("SistemaPDV.Models.DigitacaoBandeiraCaixa", b =>
                {
                    b.HasOne("SistemaPDV.Models.Caixa", null)
                        .WithMany("DigitacoesBandeiras")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPDV.Models.DigitacaoCaixa", b =>
                {
                    b.HasOne("SistemaPDV.Models.Caixa", null)
                        .WithMany("Digitacoes")
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaPDV.Models.FormaPagamento", null)
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPDV.Models.ItemVenda", b =>
                {
                    b.HasOne("SistemaPDV.Models.Produto", null)
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPDV.Models.Venda", null)
                        .WithMany("Itens")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPDV.Models.PagamentoVenda", b =>
                {
                    b.HasOne("SistemaPDV.Models.FormaPagamento", null)
                        .WithMany()
                        .HasForeignKey("FormaPagamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPDV.Models.Venda", null)
                        .WithMany("Pagamentos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SistemaPDV.Models.Produto", b =>
                {
                    b.OwnsMany("SistemaPDV.Models.ImagemProduto", "Imagens", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ArquivoOriginal")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("ArquivoThumbnail")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Descricao")
                                .HasColumnType("TEXT");

                            b1.Property<int>("ProdutoId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Tipo")
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("ProdutoId");

                            b1.ToTable("ImagemProduto");

                            b1.WithOwner()
                                .HasForeignKey("ProdutoId");
                        });

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("SistemaPDV.Models.Venda", b =>
                {
                    b.HasOne("SistemaPDV.Models.Caixa", null)
                        .WithMany()
                        .HasForeignKey("CaixaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SistemaPDV.Models.Cliente", null)
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SistemaPDV.Models.Caixa", b =>
                {
                    b.Navigation("Digitacoes");

                    b.Navigation("DigitacoesBandeiras");
                });

            modelBuilder.Entity("SistemaPDV.Models.Venda", b =>
                {
                    b.Navigation("Itens");

                    b.Navigation("Pagamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
